export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const ERROR_PRODUCT = 'ERROR_PRODUCT';
export const EDIT_PRICE_PROVEEDOR = 'EDIT_PRICE_PROVEEDOR';
export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';

export const ADD_PROVEEDOR = 'ADD_PROVEEDOR';
export const GET_PROVEEDOR = 'GET_PROVEEDOR';
export const GET_PROVEEDORES = 'GET_PROVEEDORES';
export const EDIT_PROVEEDOR = 'EDIT_PROVEEDOR';
export const ERROR_PROVEEDOR = 'ERROR_PROVEEDOR';
export const REQUEST_PROVEEDOR = 'REQUEST_PROVEEDOR';